apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: catalogv414-rhbk-fbc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/rhbk-fbc/catalogv414-rhbk-fbc@sha256:cebb19676e8eb7f8471439920a1a60ad15c2b17d526d072ac065b2e97b9de301
        name: container-image
        resources: {}
status: {}
