apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: catalogv414-rhbk-fbc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: catalogv414-rhbk-fbc
    app.kubernetes.io/part-of: rhbk-fbc
  name: catalogv414-rhbk-fbcmx5k
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: catalogv414-rhbk-fbc
    weight: 100
status: {}
