apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: catalogv414-rhbk-fbc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: catalogv414-rhbk-fbc
    app.kubernetes.io/part-of: rhbk-fbc
  name: catalogv414-rhbk-fbc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: catalogv414-rhbk-fbc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: catalogv414-rhbk-fbc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/rhbk-fbc/catalogv414-rhbk-fbc@sha256:cebb19676e8eb7f8471439920a1a60ad15c2b17d526d072ac065b2e97b9de301
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
